### ISSUE TITLE
When sending big amount of graphical objects to server, JSON with entities is empty

### ISSUE THREAD

**Issue by tiborschvartz** [gamefest2017/ants#48]
Reproducible, when 80 generated food objects are sent with SET operation to server, causing following exception (JSON in Mapper is empty string):

com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@cb8779eb; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2671)
	at com.ibm.sk.ff.gui.common.mapper.Mapper.jsonToPojo(Mapper.java:25)
	at com.ibm.sk.ff.gui.server.RequestHandler.callSet(RequestHandler.java:88)
	at com.ibm.sk.ff.gui.server.RequestHandler.handle(RequestHandler.java:63)
	at com.ibm.sk.ff.gui.server.RequestHandler.handle(RequestHandler.java:53)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:91)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:95)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:94)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:687)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:91)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:659)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:170)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:443)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
	at java.lang.Thread.run(Thread.java:785)

**Comment by The0retico** [comment]
What are the arguments of com.ibm.sk.ff.gui.client.Client.postMessage(String, String) on the clients side?

**Comment by The0retico** [comment]
Thanks to Tibor, we fixed it in pull request #50 .
