### ISSUE TITLE
NPE on food pickup

### ISSUE THREAD

**Issue by dr-evo** [gamefest2017/ants#62]
Build 5ee4561fb957ef2522c8a3d363a327be2f469350 Tournament integration - first pitch (#60)

**Steps to reproduce:**
Run server as java application  /FallFestGUI/src/com/ibm/sk/ff/gui/Main.java
Run menu main client  /Ants/src/com/ibm/sk/MenuMain.java
run tournament

**Actual result:**
Game is initialized, but crashes on first instance where ant interacts with food, with below exception

java.lang.NullPointerException
	at com.ibm.sk.ff.gui.client.GUIFacade.remove(GUIFacade.java:188)
	at com.ibm.sk.ff.gui.client.GUIFacade.sendNotYetRenderedData(GUIFacade.java:91)
	at com.ibm.sk.ff.gui.client.GUIFacade.set(GUIFacade.java:77)
	at com.ibm.sk.engine.GuiConnector.placeGuiObjects(GuiConnector.java:78)
	at com.ibm.sk.engine.ProcessExecutor.execute(ProcessExecutor.java:55)
	at com.ibm.sk.engine.matchmaking.Tournament.resolveNextMatch(Tournament.java:53)
	at com.ibm.sk.handlers.GameMenuHandler.actionPerformed(GameMenuHandler.java:58)
	at com.ibm.sk.ff.gui.client.GUIFacade.lambda$9(GUIFacade.java:236)
	at com.ibm.sk.ff.gui.client.GUIFacade$$Lambda$8/1924795731.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.ibm.sk.ff.gui.client.GUIFacade.castEvent(GUIFacade.java:236)
	at com.ibm.sk.ff.gui.client.GUIFacade.checkEvents(GUIFacade.java:219)
	at com.ibm.sk.ff.gui.client.GUIFacade.access$0(GUIFacade.java:215)
	at com.ibm.sk.ff.gui.client.GUIFacade$1.run(GUIFacade.java:54)
	at java.lang.Thread.run(Unknown Source)

**Expected result:**
no exception

**Comment by dr-evo** [comment]
Issue also occurs outside of tournament in duel.

**Comment by dr-evo** [comment]
commenting out GUIFacade.java:188 works as a temporary solution
steps are apparently not initialized
```java
steps.add(new Step(REMOVE, crate));
```

**Comment by tiborschvartz** [comment]
Fixed by Gabriel Szabo <szabo.gabriel@gmail.com> on 2017-10-19 03:38:18
